name: mypy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published
  schedule:
    - cron: "0 0 * * *"

jobs:
  release:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dev. dependencies
        run: poetry install --no-interaction

      - name: Run mypy
        run: poetry run mypy .
