name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.11"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install lazyfpl
        shell: bash
        run: |
          pip3 install -U pip
          pip3 install -e .

      - name: Run tests
        run: |
          pip3 install pytest
          pytest
